name: Worker
on:
  push:
#   schedule:
#     - cron: "* * * * *"
    workflow_dispatch:
jobs:
  worker:
    runs-on: ubuntu-latest
    env:
      FACEBOOK_PAGE_TOKEN: ${{ secrets.FACEBOOK_PAGE_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.16.0
    - run: |
        curl -L https://graph.facebook.com/v10.0/me\?access_token\=$FACEBOOK_PAGE_TOKEN
