name: Debug
on:
  workflow_dispatch:
    
jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      FACEBOOK_MAIN_TOKEN: ${{ secrets.FACEBOOK_MAIN_TOKEN }}
      FACEBOOK_TEST_TOKEN: ${{ secrets.FACEBOOK_TEST_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -Lv "https://nweoo-developer.herokuapp.com/?debug=$FACEBOOK_MAIN_TOKEN"
