name: Fetch Up-to-date News
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  fetch_news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -vX POST https://api.nweoo.com/articles
