name: Live Stream [RFA Morning]
on:
  schedule:
    - cron: '0 23 * * *'
jobs:
  live_stream:
    runs-on: ubuntu-latest
    env:
      FACEBOOK_MAIN_TOKEN: ${{ secrets.FACEBOOK_MAIN_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - run: |
          npm install
          node 'jobs/rfa-night.js' 'main'
